import type { Metadata } from "next"
import "./globals.css"
import { outfit } from "@/fonts"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/contexts/theme-provider"

export const metadata: Metadata = {
  title: "Fenrir",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("antialiased", outfit.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
